//! Android entry: the same host behind a GameActivity. The APK's assets carry the bundle
//! under `assets/Blackiron/`; saves go to the app's internal data directory.
//!
//! `BlackironActivity` (Java, generated by `blackiron export android`) forwards controller events to
//! the `Java_com_blackiron_host_BlackironInput_*` functions below and performs haptics on request.

use android_activity::AndroidApp;
use jni::objects::{JClass, JObject, JValue};
use jni::sys::{jboolean, jfloat, jint};
use jni::JNIEnv;
use winit::event_loop::EventLoop;
use winit::platform::android::EventLoopBuilderExtAndroid;

use crate::bundle::Bundle;
use crate::input::{android_push, PadEvent};
use crate::RunOptions;

#[no_mangle]
fn android_main(app: AndroidApp) {
    android_logger::init_once(android_logger::Config::default().with_max_level(log::LevelFilter::Info).with_tag("blackiron"));
    // Panics would otherwise abort silently; put the message in logcat first.
    std::panic::set_hook(Box::new(|info| log::error!("panic: {info}")));
    let bundle = Bundle::Assets(app.asset_manager());
    let title = bundle.name();
    let data_dir = app.internal_data_path().unwrap_or_else(|| std::path::PathBuf::from("/data/local/tmp"));
    // `blackiron verify` launches with extras: BLACKIRON_SNAPSHOT (file name), BLACKIRON_SNAPSHOT_FRAME,
    // BLACKIRON_TAPS ("x,y:frame;..."), BLACKIRON_FIXED_DT; the PNG lands in the app's files directory.
    let extras = intent_extras(&app);
    let snapshot = extras.get("BLACKIRON_SNAPSHOT").map(|name| data_dir.join(name));
    let snapshot_frame = extras.get("BLACKIRON_SNAPSHOT_FRAME").and_then(|v| v.parse().ok()).unwrap_or(30);
    let fixed_dt = extras.get("BLACKIRON_FIXED_DT").and_then(|v| v.parse().ok());
    let taps = extras.get("BLACKIRON_TAPS").map(|t| parse_taps(t)).unwrap_or_default();
    let exit_after_snapshot = snapshot.is_some() && extras.get("BLACKIRON_SNAPSHOT_EXIT").map(|v| v == "1").unwrap_or(false);
    let event_loop = EventLoop::builder().with_android_app(app).build().expect("event loop");
    crate::run(event_loop, RunOptions { bundle, data_dir, title, size: (1280.0, 720.0), fullscreen: true, snapshot, snapshot_frame, exit_after_snapshot, taps, engine: crate::script::EngineKind::default_for_build(), fixed_dt });
}

/// "x,y:frame;x,y:frame" into taps.
pub fn parse_taps(spec: &str) -> Vec<(f64, f64, u64)> {
    spec.split(';')
        .filter_map(|t| {
            let (xy, frame) = t.split_once(':')?;
            let (x, y) = xy.split_once(',')?;
            Some((x.trim().parse().ok()?, y.trim().parse().ok()?, frame.trim().parse().ok()?))
        })
        .collect()
}

/// String extras of the launching intent, read through JNI; empty when anything is missing.
fn intent_extras(app: &AndroidApp) -> std::collections::HashMap<String, String> {
    let mut out = std::collections::HashMap::new();
    let Ok(vm) = (unsafe { jni::JavaVM::from_raw(app.vm_as_ptr().cast()) }) else { return out };
    let Ok(mut env) = vm.attach_current_thread() else { return out };
    let activity = unsafe { JObject::from_raw(app.activity_as_ptr().cast()) };
    let keys = ["BLACKIRON_SNAPSHOT", "BLACKIRON_SNAPSHOT_FRAME", "BLACKIRON_TAPS", "BLACKIRON_FIXED_DT", "BLACKIRON_SNAPSHOT_EXIT"];
    let r: jni::errors::Result<()> = (|| {
        let intent = env.call_method(&activity, "getIntent", "()Landroid/content/Intent;", &[])?.l()?;
        if intent.is_null() {
            return Ok(());
        }
        for key in keys {
            let k = env.new_string(key)?;
            let v = env.call_method(&intent, "getStringExtra", "(Ljava/lang/String;)Ljava/lang/String;", &[JValue::Object(&k)])?.l()?;
            if !v.is_null() {
                let s: String = env.get_string(&jni::objects::JString::from(v))?.into();
                out.insert(key.to_string(), s);
            }
        }
        Ok(())
    })();
    if r.is_err() {
        let _ = env.exception_clear();
    }
    out
}

/// A controller axis moved (UI thread). Queued for the game loop's next poll.
#[no_mangle]
pub extern "system" fn Java_com_blackiron_host_BlackironInput_nativeAxis(_env: JNIEnv, _class: JClass, device: jint, axis: jint, value: jfloat) {
    android_push(PadEvent::Axis { device, axis, value });
}

/// A controller button changed (UI thread).
#[no_mangle]
pub extern "system" fn Java_com_blackiron_host_BlackironInput_nativeButton(_env: JNIEnv, _class: JClass, device: jint, key: jint, down: jboolean) {
    android_push(PadEvent::Button { device, key, down: down != 0 });
}

/// A controller was unplugged (UI thread); its held keys release.
#[no_mangle]
pub extern "system" fn Java_com_blackiron_host_BlackironInput_nativeRemoved(_env: JNIEnv, _class: JClass, device: jint) {
    android_push(PadEvent::Removed { device });
}

/// Haptics through `BlackironInput.haptic`, which picks a system vibration effect; best effort.
pub fn haptic(kind: &str) {
    let ctx = ndk_context::android_context();
    let Ok(vm) = (unsafe { jni::JavaVM::from_raw(ctx.vm().cast()) }) else { return };
    let Ok(mut env) = vm.attach_current_thread() else { return };
    // ndk_context hands out the Application, which is Context enough for the vibrator.
    let context = unsafe { JObject::from_raw(ctx.context().cast()) };
    if call_haptic(&mut env, &context, kind).is_err() {
        // A project generated before BlackironActivity existed has no helper class; stay quiet.
        let _ = env.exception_clear();
    }
}

/// Read text through TalkBack when it is on, via the generated BlackironInput helper.
pub fn announce(text: &str) {
    let ctx = ndk_context::android_context();
    let Ok(vm) = (unsafe { jni::JavaVM::from_raw(ctx.vm().cast()) }) else { return };
    let Ok(mut env) = vm.attach_current_thread() else { return };
    let context = unsafe { JObject::from_raw(ctx.context().cast()) };
    if call_static_text(&mut env, &context, "announce", text).is_err() {
        let _ = env.exception_clear();
    }
}

fn call_static_text(env: &mut JNIEnv, context: &JObject, method: &str, text: &str) -> jni::errors::Result<()> {
    let loader = env.call_method(context, "getClassLoader", "()Ljava/lang/ClassLoader;", &[])?.l()?;
    let name = env.new_string("com.blackiron.host.BlackironInput")?;
    let cls = env.call_method(&loader, "loadClass", "(Ljava/lang/String;)Ljava/lang/Class;", &[JValue::Object(&name)])?.l()?;
    let cls = JClass::from(cls);
    let arg = env.new_string(text)?;
    env.call_static_method(&cls, method, "(Landroid/content/Context;Ljava/lang/String;)V", &[JValue::Object(context), JValue::Object(&arg)])?;
    Ok(())
}

fn call_haptic(env: &mut JNIEnv, context: &JObject, kind: &str) -> jni::errors::Result<()> {
    // FindClass from a native thread only sees the system loader; go through the app's.
    let loader = env.call_method(context, "getClassLoader", "()Ljava/lang/ClassLoader;", &[])?.l()?;
    let name = env.new_string("com.blackiron.host.BlackironInput")?;
    let cls = env.call_method(&loader, "loadClass", "(Ljava/lang/String;)Ljava/lang/Class;", &[JValue::Object(&name)])?.l()?;
    let cls = JClass::from(cls);
    let kind = env.new_string(kind)?;
    env.call_static_method(&cls, "haptic", "(Landroid/content/Context;Ljava/lang/String;)V", &[JValue::Object(context), JValue::Object(&kind)])?;
    Ok(())
}
