// Builds the kernel for every target the engine ships to:
//   - WebAssembly, embedded as base64 in src/kernel/kernel.wasm.ts (committed, so tests and
//     builds work without a Rust toolchain)
//   - an XCFramework of static libraries for the iOS simulator and devices, in kernel/dist/
// Usage: bun kernel/build.ts [--web-only]

import { mkdir, rm } from "node:fs/promises";
import { join } from "node:path";

const root = import.meta.dir;
const webOnly = process.argv.includes("--web-only");
const iosOnly = process.argv.includes("--ios-only");
if (webOnly && iosOnly) throw new Error("Choose --web-only or --ios-only");
if (iosOnly && process.platform !== "darwin")
  throw new Error("iOS kernel requires macOS/Xcode");

function run(cmd: string[], cwd = root): void {
  const p = Bun.spawnSync(cmd, { cwd, stdout: "inherit", stderr: "inherit" });
  if (p.exitCode !== 0) throw new Error(`${cmd.join(" ")} failed`);
}

if (!iosOnly) {
  run([
    "cargo",
    "rustc",
    "--locked",
    "--release",
    "--quiet",
    "--target",
    "wasm32-unknown-unknown",
    "--crate-type",
    "cdylib",
  ]);
  const wasm = await Bun.file(
    join(root, "target/wasm32-unknown-unknown/release/kiln_kernel.wasm"),
  ).arrayBuffer();
  const b64 = Buffer.from(wasm).toString("base64");
  await Bun.write(
    join(root, "..", "src", "kernel", "kernel.wasm.ts"),
    `// Generated by kernel/build.ts from kernel/src/lib.rs. Do not edit.\nexport const KERNEL_WASM_BYTES = ${wasm.byteLength};\nexport const KERNEL_WASM_BASE64 =\n  "${b64}";\n`,
  );
  console.log(
    `  kernel.wasm ${(wasm.byteLength / 1024).toFixed(1)} KB -> src/kernel/kernel.wasm.ts`,
  );

  // Physics is a separate module, fetched by a game only when it enables physics.
  run([
    "cargo",
    "rustc",
    "--locked",
    "--release",
    "--quiet",
    "--features",
    "physics",
    "--target",
    "wasm32-unknown-unknown",
    "--crate-type",
    "cdylib",
    "--target-dir",
    "target/physics",
  ]);
  const physics = await Bun.file(
    join(
      root,
      "target/physics/wasm32-unknown-unknown/release/kiln_kernel.wasm",
    ),
  ).arrayBuffer();
  await Bun.write(join(root, "..", "src", "kernel", "physics.wasm"), physics);
  console.log(
    `  physics.wasm ${(physics.byteLength / 1024).toFixed(1)} KB -> src/kernel/physics.wasm`,
  );

  // The audio worklet loads the codec build when it is served, so music can stream on the web.
  run([
    "cargo",
    "rustc",
    "--locked",
    "--release",
    "--quiet",
    "--features",
    "codecs",
    "--target",
    "wasm32-unknown-unknown",
    "--crate-type",
    "cdylib",
    "--target-dir",
    "target/codecs",
  ]);
  const codecs = await Bun.file(
    join(root, "target/codecs/wasm32-unknown-unknown/release/kiln_kernel.wasm"),
  ).arrayBuffer();
  await Bun.write(join(root, "..", "src", "kernel", "audio.wasm"), codecs);
  console.log(
    `  audio.wasm ${(codecs.byteLength / 1024).toFixed(1)} KB -> src/kernel/audio.wasm`,
  );
}

if (!webOnly && process.platform === "darwin") {
  const targets = ["aarch64-apple-ios-sim", "aarch64-apple-ios"];
  const libs: string[] = [];
  for (const t of targets) {
    run([
      "cargo",
      "rustc",
      "--locked",
      "--release",
      "--quiet",
      "--features",
      "physics,physics3d,render,codecs",
      "--target",
      t,
      "--crate-type",
      "staticlib",
    ]);
    libs.push(join(root, "target", t, "release", "libkiln_kernel.a"));
  }
  const out = join(root, "dist", "KilnKernel.xcframework");
  await rm(out, { recursive: true, force: true });
  await mkdir(join(root, "dist"), { recursive: true });
  const args = ["xcodebuild", "-create-xcframework"];
  for (const lib of libs)
    args.push("-library", lib, "-headers", join(root, "include"));
  args.push("-output", out);
  run(args);
  console.log("  KilnKernel.xcframework -> kernel/dist/");
}
